version: '3.8'
services:
  backend:
    context: .
    dockerfile : docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:harkirt@postgres:5432/postgres
    depends_on:
      - postgres
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.fr
      args:
        - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:harkirt@postgres:5432/postgres
    depends_on:
      - postgres
  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
     -"8001:8001"
    environment:
      - POSTGRES_PASSWORD = postgres
    ports:
     - "5432:5432"
    volumes:
       - postgres_data:/var/lib/postgres/data
volumes:
  postgres_data:
    