name: backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        users: docker/login-action@v2
        with: username:${{secrets.DOCKERHUB_USERNAME}}
          password:${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@4
        with:
          context: .
          file: docker/Dockerfile.backend
          push: true
          tags: docker_learn/todo-backend:${{github.sha}} ## github.sha is version which generate on push commit
